name: Deploy to Oracle VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/AWS-SERVER
            git fetch --all
            git reset --hard origin/main   # <— ensures no dirty files
            npm install @whiskeysockets/baileys@latest
            npm install                        
            pm2 restart aws-v2 || pm2 start src/index.js --name aws-v2
            sleep 60
            node scripts/notifyUpdate.js
  
